# Zoo Animal Classification

In [1]:
import pandas as pd
import numpy as np


In [2]:
data= pd.read_csv('zoo.csv',index_col=None,header=0)
data

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

In [3]:
#

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  101 non-null    object
 1   hair         101 non-null    int64 
 2   feathers     101 non-null    int64 
 3   eggs         101 non-null    int64 
 4   milk         101 non-null    int64 
 5   airborne     101 non-null    int64 
 6   aquatic      101 non-null    int64 
 7   predator     101 non-null    int64 
 8   toothed      101 non-null    int64 
 9   backbone     101 non-null    int64 
 10  breathes     101 non-null    int64 
 11  venomous     101 non-null    int64 
 12  fins         101 non-null    int64 
 13  legs         101 non-null    int64 
 14  tail         101 non-null    int64 
 15  domestic     101 non-null    int64 
 16  catsize      101 non-null    int64 
 17  class_type   101 non-null    int64 
dtypes: int64(17), object(1)
memory usage: 14.3+ KB


In [5]:
data.describe(include='all')

animal_name        hair    feathers        eggs        milk  \
count          101  101.000000  101.000000  101.000000  101.000000   
unique         100         NaN         NaN         NaN         NaN   
top           frog         NaN         NaN         NaN         NaN   
freq             2         NaN         NaN         NaN         NaN   
mean           NaN    0.425743    0.198020    0.584158    0.405941   
std            NaN    0.496921    0.400495    0.495325    0.493522   
min            NaN    0.000000    0.000000    0.000000    0.000000   
25%            NaN    0.000000    0.000000    0.000000    0.000000   
50%            NaN    0.000000    0.000000    1.000000    0.000000   
75%            NaN    1.000000    0.000000    1.000000    1.000000   
max            NaN    1.000000    1.000000    1.000000    1.000000   

          airborne     aquatic    predator     toothed    backbone  \
count   101.000000  101.000000  101.000000  101.000000  101.000000   
unique         NaN         NaN         NaN         NaN         NaN   
top            NaN         NaN         NaN         NaN         NaN   
freq           NaN         NaN         NaN         NaN         NaN   
mean      0.237624    0.356436    0.554455    0.603960    0.821782   
std       0.427750    0.481335    0.499505    0.491512    0.384605   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       0.000000    0.000000    0.000000    0.000000    1.000000   
50%       0.000000    0.000000    1.000000    1.000000    1.000000   
75%       0.000000    1.000000    1.000000    1.000000    1.000000   
max       1.000000    1.000000    1.000000    1.000000    1.000000   

          breathes    venomous        fins        legs        tail  \
count   101.000000  101.000000  101.000000  101.000000  101.000000   
unique         NaN         NaN         NaN         NaN         NaN   
top            NaN         NaN         NaN         NaN         NaN   
freq           NaN         NaN         NaN         NaN         NaN   
mean      0.792079    0.079208    0.168317    2.841584    0.742574   
std       0.407844    0.271410    0.376013    2.033385    0.439397   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000    0.000000    0.000000    2.000000    0.000000   
50%       1.000000    0.000000    0.000000    4.000000    1.000000   
75%       1.000000    0.000000    0.000000    4.000000    1.000000   
max       1.000000    1.000000    1.000000    8.000000    1.000000   

          domestic     catsize  class_type  
count   101.000000  101.000000  101.000000  
unique         NaN         NaN         NaN  
top            NaN         NaN         NaN  
freq           NaN         NaN         NaN  
mean      0.128713    0.435644    2.831683  
std       0.336552    0.498314    2.102709  
min       0.000000    0.000000    1.000000  
25%       0.000000    0.000000    1.000000  
50%       0.000000    0.000000    2.000000  
75%       0.000000    1.000000    4.000000  
max       1.000000    1.000000    7.000000

In [6]:
data.shape

(101, 18)

In [7]:
data.columns

Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type'],
      dtype='object')

In [8]:
## finding the missing values

print(data.isnull().sum())



animal_name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
class_type     0
dtype: int64


In [9]:
# transforming categorical variable into an numerical variable

from sklearn.preprocessing import LabelEncoder
colname=['animal_name']

le=LabelEncoder()

for x in colname:
    data[x]=le.fit_transform(data[x])

In [10]:
data.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0            0     1         0     0     1         0        0         1   
1            1     1         0     0     1         0        0         0   
2            2     0         0     1     0         0        1         1   
3            3     1         0     0     1         0        0         1   
4            4     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [11]:
# creating X and Y
# train data

X = data.values[:,0:-1]
Y = data.values[:,-1]
Y= Y.astype(int)


In [12]:
# splitting the data into 80 - 20 %

from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [13]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(70, 17)
(70,)
(31, 17)
(31,)


In [14]:
from sklearn.svm import SVC

svc_model = SVC(kernel= 'linear', C=1,gamma = 0.01)

svc_model.fit(X_train , Y_train)

Y_pred=svc_model.predict(X_test)

print(list(Y_pred))

[2, 1, 7, 6, 4, 1, 1, 1, 2, 7, 2, 4, 1, 6, 4, 1, 5, 2, 1, 4, 7, 5, 2, 7, 1, 1, 2, 2, 1, 1, 1]


In [15]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


print(confusion_matrix(Y_test,Y_pred))
print()
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[12  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  1  0  0  1  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  4]]

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       0.86      1.00      0.92         6
           3       0.00      0.00      0.00         2
           4       1.00      1.00      1.00         4
           5       0.50      1.00      0.67         1
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         4

    accuracy                           0.94        31
   macro avg       0.77      0.86      0.80        31
weighted avg       0.89      0.94      0.91        31

0.9354838709677419


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
